### PR TITLE
Rewrite the project for v11, apply code best practices, add vite configuration, add workflow github action

### PR DESCRIPTION
**Pull request by p4535992**

### CODE REVIEW

**Comment by WBHarry** [comment]
Wow, impressive to do this for the little module 😄
I have indeed not really been into module development for a long time due to GM:ing a whole lot, and now recently working on developing a new foundry system.

I'll definately merge this on in, although considering I probably won't spend time on the module going forward, I'd be happy to let you take it over if you're up for that.

**Comment by p4535992** [comment]
@WBHarry I would hate to see this little module go into oblivion, I don't think I will be implementing new things at least anytime soon, but I will work hard to keep it compatible. I take advantage of your generosity to ask for ownership of the module .

**Comment by WBHarry** [comment]
@p4535992 Awesome. Now, I haven't transfered a repository before, but as far as I understand you can't have both a fork and the main repository.
I don't know if there's another way than deleting the fork. At least that should be safe to do now since I did merge these commits into it.
image

**Comment by p4535992** [comment]
**a no need to do anything on your side** i just ask to the foundryvtt team to transfet the ownership to my user .
If we want to use current github repositry, just invite me as collaborator on this project or i will use my fork as new github repository (if in the future you want to retake the module there is no problem)

**Comment by WBHarry** [comment]
Alright, seems like you know how to proceed with it :smile:
All the best

**Pull request merged**
